spring.application.name=meetingroomapi

spring.datasource.url=jdbc:mysql://localhost:3307/meetingroomdb
spring.datasource.username=root
spring.datasource.password=Temp2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.open-in-view=false